discourse_anon_usernames:
  discourse_anon_usernames_enabled:
    default: false
    client: true
  only_generated_usernames:
    default: false
    client: true
  random_words_list:
    type: list
    default: "Apple|Grape|Orange|Pineapple|Fig"
    client: true
